on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rmecr1.azurecr.io
        username: ${{ secrets.acr_rmecr1_username }}
        password: ${{ secrets.acr_rmecr1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t rmecr1.azurecr.io/rmeaks1:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push rmecr1.azurecr.io/rmeaks1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rmeaks1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rmeaks1a0c2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rmeaks1a0c2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rmeaks1a0c2
        container-registry-url: rmecr1.azurecr.io
        container-registry-username: ${{ secrets.acr_rmecr1_username }}
        container-registry-password: ${{ secrets.acr_rmecr1_password }}
        secret-name: rmeaks1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: rmeaks1a0c2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          rmecr1.azurecr.io/rmeaks1:${{ github.sha }}
        imagepullsecrets: |
          rmeaks1dockerauth
